//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mamirmi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int id { get; set; }
        public string Personaid { get; set; }
        public string cuenta_BN { get; set; }
        public string cuenta_BP { get; set; }
        public string Profesion { get; set; }
        public string Estudios { get; set; }
        public string Manipulacion_Alimentos { get; set; }
        public string Enfermedades { get; set; }
        public string carne { get; set; }
        public string experiencia { get; set; }
        public string fecha_Ingreso { get; set; }
        public string departamento { get; set; }
        public string descripcion_Salida { get; set; }
        public string fecha_Salida { get; set; }
        public string estado { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
