//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mamirmi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public string ID { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string carne { get; set; }
        public System.DateTime fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> fecha_Salida { get; set; }
        public string departamento { get; set; }
        public bool estado { get; set; }
        public string cuenta_BN { get; set; }
        public string cuenta_BP { get; set; }
        public Nullable<int> numeroComprobante { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
