//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mamirmi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hora
    {
        public int id { get; set; }
        public string Personaid { get; set; }
        public Nullable<System.DateTime> fecha_Inicial { get; set; }
        public Nullable<System.DateTime> fecha_Final { get; set; }
        public Nullable<decimal> horas_Ordinarias { get; set; }
        public Nullable<decimal> horas_Extra { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
