//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mamirmi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int ID { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public int edad { get; set; }
        public string nacionalidad { get; set; }
        public string EstadoCivil { get; set; }
        public string direccion { get; set; }
        public string sexo { get; set; }
        public Nullable<int> Hijos { get; set; }
        public System.DateTime fecha_de_ingreso { get; set; }
    }
}
