//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mamirmi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Aguinaldo = new HashSet<Aguinaldo>();
            this.Empleado = new HashSet<Empleado>();
            this.Hora = new HashSet<Hora>();
            this.Incapacidad = new HashSet<Incapacidad>();
            this.Salario = new HashSet<Salario>();
            this.Vacaciones = new HashSet<Vacaciones>();
            this.Telefono = new HashSet<Telefono>();
        }
    
        public string id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public byte edad { get; set; }
        public string nacionalidad { get; set; }
        public string EstadoCivil { get; set; }
        public string direccion { get; set; }
        public string sexo { get; set; }
        public Nullable<byte> Hijos { get; set; }
        public string fecha_de_ingreso { get; set; }
    
        public virtual ICollection<Aguinaldo> Aguinaldo { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<Hora> Hora { get; set; }
        public virtual ICollection<Incapacidad> Incapacidad { get; set; }
        public virtual ICollection<Salario> Salario { get; set; }
        public virtual ICollection<Vacaciones> Vacaciones { get; set; }
        public virtual ICollection<Telefono> Telefono { get; set; }
    }
}
