//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mamirmi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salario
    {
        public int id { get; set; }
        public string Personaid { get; set; }
        public decimal salario_Bruto { get; set; }
        public decimal salario_Neto { get; set; }
        public string Jornada { get; set; }
        public decimal CCSS { get; set; }
        public Nullable<decimal> ahorro_Navidad { get; set; }
        public Nullable<decimal> ahorro_Escolar { get; set; }
        public Nullable<System.DateTime> fecha_Salario { get; set; }
        public Nullable<decimal> Otros { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
